UsersManagement/Models/IdentityModels/Role.cs
using Microsoft.AspNetCore.Identity;

namespace UsersManagement.Models.IdentityModels
{
    public class Role : IdentityRole
    {
        public string NameAr { get; set; }
    }
}

UsersManagement/ViewModels/IdentityViewModels/RoleViewModel.cs
namespace UsersManagement.ViewModels.IdentityViewModels
{
    public class RoleViewModel
    {
        public string RoleID { get; set; }
        public string NameAr { get; set; }
        public string NameEn { get; set; }
        public bool IsActive { get; set; }
    }
}

UsersManagement/Controllers/IdentityControllers/RolesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using UsersManagement.Enums;
using UsersManagement.Models.IdentityModels;
using UsersManagement.ViewModels.IdentityViewModels;

namespace UsersManagement.Controllers.IdentityControllers
{
    [Authorize(Roles = "Admin" )]
    public class RolesController : Controller
    {
        private readonly RoleManager<Role> _roleManager;

        public RolesController(RoleManager<Role> roleManager)
        {
            _roleManager = roleManager;
        }

        public async Task<IActionResult> Index()
        {
            var roles = await _roleManager.Roles.ToListAsync();
           
            return View(roles);
        }


        public async Task<IActionResult> CreateRole()
        {

            return View();
        }


        [HttpPost]
        public async Task<IActionResult> CreateRole(RoleFormViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            if(await _roleManager.Roles.AnyAsync(r => r.NameAr == model.NameAr.Trim()))
            {
                ModelState.AddModelError("NameAr", "This Role Already Exists!!");
                return View(model);
            }

            if (await _roleManager.RoleExistsAsync(model.NameEn.Trim()))
            {
                ModelState.AddModelError("NameEn", "This Role Already Exists!!");
                return View(model);
            }

            await _roleManager.CreateAsync(new Role 
            {  
                Name = model.NameEn.Trim(),
                NameAr = model.NameAr.Trim() 
            });

            return RedirectToAction("Index", "Users");
        }
    }
}

UsersManagement/Views/Roles/CreateRole.cshtml
@model RoleFormViewModel

@{
    ViewData["Title"] = "Add new role";
}

<h3 class="text-center text-success">@ViewData["Title"]</h3>
<diV class="container">
    <form method="post" asp-controller="Roles" asp-action="CreateRole" class="row justify-content-center">
        <div class="col-md-3 p-4 rounded-3" style="background-color: #3f51b5;" >
            <div class="row g-3">
                <div class="col-12">
                    <label asp-for="NameEn" class="form-label text-light"></label>
                    <input asp-for="NameEn" class="form-control" >
                    <span asp-validation-for="NameEn"></span>
                </div>
                <div class="col-12">
                    <label asp-for="NameAr" class="form-label text-light"></label>
                    <input asp-for="NameAr" class="form-control" >
                    <span asp-validation-for="NameAr"></span>
                </div>
                <div class="col-12">
                    <button type="submit" class="btn btn-success w-100 px-3">Add</button>
                </div>
            </div>
        </div>
    </form>
    <div>
        <a class="btn btn-outline-secondary px-4" asp-area="Identity" asp-controller="Users" asp-action="Index" >Back</a>
    </div>
</diV>



@section Scripts {
        <partial name="_ValidationScriptsPartial" />
}

UsersManagement/Views/Roles/Index.cshtml
@model IEnumerable<Role>

@{
    ViewData["Title"] = "Roles";
}

<h1 class="text-center text-success">@ViewData["Title"]</h1>


<table class="table text-center align-middle">
    <thead>
        <tr>
            <th>NameAr</th>
            <th>NameEn</th>
        </tr>
    </thead>
    <tbody>
        @if (!Model.Any())
        {
            <h4 class="text-center text-danger">No Roles Were Found!!</h4>
        }
        else
        {
            foreach (var role in Model)
            {
                <tr>
                    <td>@role.NameAr</td>
                    <td>@role.Name</td>
                </tr>
            }
        }
    </tbody>
</table>